name: SonarCloud Scan

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        working-directory: sonar-coverage-demo
        run: npm install

      - name: Run Tests With Coverage
        working-directory: sonar-coverage-demo
        run: npm test

      - name: Verify Coverage File
        run: |
          ls -la sonar-coverage-demo/coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}